spring.application.name=adk-demo
spring.config.import=optional:file:.env[.properties]
gemini.api-key=${GEMINI_API_KEY}
plivo.auth-key=${PLIVO_AUTH_KEY}
plivo.auth-token=${PLIVO_AUTH_TOKEN}

#logging.level.org.springframework.boot.context.properties=DEBUG
#logging.level.com.google.adk=DEBUG